#frontend docker file
FROM node:24-alpine AS build

ARG VITE_API_BASE=http://localhost:8000

ENV VITE_API_BASE$=${VITE_API_BASE}

WORKDIR /app

COPY package.json  ./

RUN npm install

COPY . . 
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

