services:
  postgres:
    image: postgres:18-alpine
    container_name: pagasa-postgres
    environment:
      POSTGRES_USER: pagasa
      POSTGRES_PASSWORD: pagasa
      POSTGRES_DB: pagasa
    ports: 
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
  redis:
    image: redis:8
    container_name: pagasa-redis
    ports:
      - 127.0.0.1:6379:6379
  backend:
    image: pagasa-weather-demo-app-backend:latest
    container_name: pagasa-backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    environment:
      APP_VERSION: "1.0.0"
      GIT_SHA: "local"
      POSTGRES_DB: pagasa
      POSTGRES_USER: pagasa
      POSTGRES_PASSWORD: pagasa
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    restart: unless-stopped
  frontend:
    image: pagasa-weather-demo-app-frontend:latest
    container_name: pagasa-frontend
    ports:
      - 80:80
    depends_on:
      - backend


volumes:
  postgres_data:
